name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          printf "org.gradle.jvmargs=-Xmx2048m\nandroid.useAndroidX=true\nandroid.enableJetifier=true" > gradle.properties
          chmod +x gradlew || true
          gradle assembleDebug --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: app/build/outputs/apk/debug/*.apk
          
